### ISSUE TITLE
Error at line 1

### ISSUE THREAD

**Issue by eraumavez** [aviaryan/initranslator#1]
Error at line 1

This line does not contain a recognized action.
Without downloading all files, if we download all files (not just Initranslator.ahk) we will have another error in Line 26 (This line does not contain a recognized action.)

Regards

**Comment by aviaryan** [comment]
Make sure you are AutoHotkey (v1.1+) from http://ahkscript.org/
@eraumavez @Anime4000 You were using AHK Basic (v1.0+) most probably.
